apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incident-mcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "incident-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incident-mcp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "incident-mcp.fullname" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "incident-mcp.fullname" . }}
          env:
            - name: INCIDENT_MCP_SNOW_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERVICE_NOW_INSTANCE
            - name: INCIDENT_MCP_SNOW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERVICE_NOW_USERNAME
            - name: INCIDENT_MCP_SNOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERVICE_NOW_PASSWORD
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
