{{- if not .Values.servicenow.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incident-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incident-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  INCIDENT_MCP_SNOW_INSTANCE: {{ .Values.servicenow.snowInstance | quote }}
  INCIDENT_MCP_SNOW_USERNAME: {{ .Values.servicenow.snowUsername | quote }}
  INCIDENT_MCP_SNOW_PASSWORD: {{ .Values.servicenow.snowPassword | quote }}
{{- end }}
