apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incident-mcp
spec:
  project: default

  source:
    repoURL: https://github.com/glroland/incident-mcp.git
    targetRevision: HEAD
    path: deploy/helm
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: incident-mcp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
